name: Assets

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  download-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⤵️ Get Kubeconform binary
        run: |
          ./.github/scripts/get-kubeconform-binary.sh
      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: 🎯 Get version
        run: |
          BINARY_VERSION=$(./Devantler.KubeconformCLI/runtimes/linux-x64/native/kubeconform-linux-x64 -v)
          echo "BINARY_VERSION=$BINARY_VERSION" >> $GITHUB_ENV
      - name: ✍🏻 Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Kubeconform binary to ${{ env.BINARY_VERSION }}
          title: Update Kubeconform binary
          body: |
            This PR updates the Kubeconform binary used by Devantler.KubeconformCLI to ${{ env.BINARY_VERSION }}.
          branch: update-kubeconform-binary
          delete-branch: true
          labels: dependencies
          reviewers: devantler
          assignees: devantler
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
