name: Assets

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  download-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⤵️ Get Kubeconform binary
        run: |
          ./.github/scripts/get-kubeconform-binary.sh
      - name: ✍🏻 Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Kubeconform binary
          title: Update Kubeconform binary
          body: |
            This PR updates the Kubeconform binary used by Devantler.AgeCLI to the latest version.
          branch: update-kubeconform-binary
          delete-branch: true
          labels: dependencies
          reviewers: devantler
          assignees: devantler
          signoff: true
